-- ID: iCoder0020
-- PROG: Asian Population
-- LANG: SQL                

SELECT COUNTRY.CONTINENT, SUM(CITY.POPULATION)
FROM CITY JOIN COUNTRY
WHERE CITY.COUNTRYCODE = COUNTRY.CODE AND COUNTRY.CONTINENT = 'ASIA'
GROUP BY COUNTRY.CONTINENT;
