-- ID: iCoder0020
-- PROG: Contest Leaderboard
-- LANG: SQL                

SELECT H.HACKER_ID, H.NAME, T.TOTAL_SCORE
FROM HACKERS AS H JOIN
(
    SELECT H1.HACKER_ID, SUM(T1.MAX_SCORE) AS TOTAL_SCORE
    FROM HACKERS AS H1,
    (
        SELECT S1.HACKER_ID, S1.SUBMISSION_ID, MAX(S1.SCORE) AS MAX_SCORE
        FROM SUBMISSIONS AS S1
        GROUP BY S1.HACKER_ID, S1.SUBMISSION_ID
    )AS T1
    WHERE T1.HACKER_ID = H1.HACKER_ID
    GROUP BY H1.HACKER_ID
)AS T
WHERE H.HACKER_ID = T.HACKER_ID AND T.TOTAL_SCORE>0
ORDER BY T.TOTAL_SCORE DESC, H.HACKER_ID ASC;