-- ID: iCoder0020
-- PROG: The Report
-- LANG: SQL                

SELECT IF(G.GRADE>=8,S.NAME,NULL), G.GRADE, S.MARKS
FROM STUDENTS AS S, GRADES AS G 
WHERE S.MARKS >= G.MIN_MARK AND S.MARKS <= G.MAX_MARK
ORDER BY G.GRADE DESC, S.NAME ASC, S.MARKS ASC;
