-- ID: iCoder0020
-- PROG: Top Competitors
-- LANG: SQL                

SELECT H.HACKER_ID, H.NAME, T1.CNT
FROM HACKERS AS H JOIN
(
    SELECT H1.HACKER_ID, 
    SUM(IF(D1.DIFFICULTY_LEVEL = C1.DIFFICULTY_LEVEL AND C1.CHALLENGE_ID = S1.CHALLENGE_ID
    AND H1.HACKER_ID = S1.HACKER_ID AND S1.SCORE = D1.SCORE, 1, 0)) AS CNT
    FROM HACKERS AS H1 JOIN DIFFICULTY AS D1 JOIN SUBMISSIONS AS S1 JOIN CHALLENGES AS C1
    GROUP BY H1.HACKER_ID
) AS T1
WHERE H.HACKER_ID = T1.HACKER_ID AND T1.CNT > 1
ORDER BY T1.CNT DESC, H.HACKER_ID ASC;
